version:    "3.7"
services:
   
    frontend:
        node: node
        build:
            context: .
            dockerfile: dockerfile
        stdin_open: true
        tty: true
        environment:
            CHOKIDAR_USEPOLLING: "true"
        ports:
            - "3000:3000"
        volumes:
            - "./packages/frontend/src:/usr/titaneum/packages/frontend/src"
            - "./packages/frontend/public:/usr/titaneum/packages/frontend/public"
            - "./packages/frontend/package.json:/usr/titaneum/packages/frontend/package.json"